### ISSUE TITLE
关于段落模式的小标题

### ISSUE THREAD

**Issue by NorthPoet** [frostime/sy-bq-callout#8]
![image](https://github.com/frostime/sy-bq-callout/assets/93069489/3228b058-5bb9-4e15-9a65-274051e7e9b8)

你好！这里的段落模式的小标题可以改成加粗的样式吗

**Comment by frostime** [comment]
把这个代码粘贴到代码片段或者插件的自定义 css 里面：
```css
:root {
    --callout-small-fc-font-weight: 700;
}
```
